modLoader="javafml"
loaderVersion="[40,)"
license="CC BY-NC-ND 4.0"

[[mods]]
modId="legendarytooltips"
version="${file.jarVersion}"
displayName="Legendary Tooltips"
displayURL="https://anthonyhilyard.com/"
updateJSONURL="https://mc-update-check.anthonyhilyard.com/532127"
logoFile="icon.png"
authors="Grend"
description='''Gives rare items a fancy tooltip and adds additional tooltip configuration options.'''

[[dependencies.legendarytooltips]]
	modId="forge"
	mandatory=true
	versionRange="[40.1,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="minecraft"
	mandatory=true
	versionRange="[1.18.2,1.19)"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="iceberg"
	mandatory=true
	versionRange="[1.0.44,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="equipmentcompare"
	mandatory=false
	versionRange="[1.2.10,)"
	ordering="NONE"
	side="BOTH"

[[dependencies.legendarytooltips]]
	modId="prism"
	mandatory=true
	versionRange="[1.0.1,)"
	ordering="NONE"
	side="BOTH"